import type {
  Shipment,
  Carrier,
  TrackingEvent,
  Route,
  WarehouseMetrics,
  PortDwellRisk,
  DockAppointmentRisk,
} from "./types";

export const demoCarriers: Carrier[] = [
  {
    id: "car_001",
    name: "Atlas Freight Logistics",
    code: "AFL",
    status: "active",
    onTimeRate: 96,
    avgTransitDays: 3.2,
    activeShipments: 42,
    totalShipments: 2840,
    rating: 4.8,
  },
  {
    id: "car_002",
    name: "Pacific Route Express",
    code: "PRE",
    status: "active",
    onTimeRate: 88,
    avgTransitDays: 4.7,
    activeShipments: 38,
    totalShipments: 1950,
    rating: 4.3,
  },
  {
    id: "car_003",
    name: "Continental Rail & Road",
    code: "CRR",
    status: "active",
    onTimeRate: 91,
    avgTransitDays: 2.9,
    activeShipments: 55,
    totalShipments: 4120,
    rating: 4.5,
  },
  {
    id: "car_004",
    name: "Global Maritime Shipping",
    code: "GMS",
    status: "under_review",
    onTimeRate: 72,
    avgTransitDays: 9.4,
    activeShipments: 15,
    totalShipments: 890,
    rating: 3.2,
  },
  {
    id: "car_005",
    name: "SkyCargo Air Freight",
    code: "SCA",
    status: "active",
    onTimeRate: 99,
    avgTransitDays: 0.8,
    activeShipments: 28,
    totalShipments: 1620,
    rating: 4.9,
  },
];

export const demoRoutes: Route[] = [
  {
    id: "rte_001",
    name: "West Coast Express",
    origin: "Los Angeles, CA",
    destination: "Seattle, WA",
    distance: 1825,
    avgTransitHours: 18,
    segments: [
      {
        from: "Los Angeles, CA",
        to: "Sacramento, CA",
        distanceKm: 620,
        mode: "road",
        avgHours: 6,
      },
      {
        from: "Sacramento, CA",
        to: "Portland, OR",
        distanceKm: 930,
        mode: "road",
        avgHours: 8,
      },
      {
        from: "Portland, OR",
        to: "Seattle, WA",
        distanceKm: 275,
        mode: "road",
        avgHours: 4,
      },
    ],
    waypoints: ["Los Angeles, CA", "Sacramento, CA", "Portland, OR", "Seattle, WA"],
    optimized: true,
  },
  {
    id: "rte_002",
    name: "Midwest Corridor",
    origin: "Chicago, IL",
    destination: "Dallas, TX",
    distance: 1490,
    avgTransitHours: 22,
    segments: [
      {
        from: "Chicago, IL",
        to: "St. Louis, MO",
        distanceKm: 470,
        mode: "rail",
        avgHours: 8,
      },
      {
        from: "St. Louis, MO",
        to: "Dallas, TX",
        distanceKm: 1020,
        mode: "road",
        avgHours: 14,
      },
    ],
    waypoints: ["Chicago, IL", "St. Louis, MO", "Dallas, TX"],
    optimized: true,
  },
  {
    id: "rte_003",
    name: "Transatlantic Route",
    origin: "New York, NY",
    destination: "Rotterdam, NL",
    distance: 5820,
    avgTransitHours: 240,
    segments: [
      {
        from: "New York, NY",
        to: "Rotterdam, NL",
        distanceKm: 5820,
        mode: "sea",
        avgHours: 240,
      },
    ],
    waypoints: ["New York, NY", "Rotterdam, NL"],
    optimized: false,
  },
  {
    id: "rte_004",
    name: "Southeast Corridor",
    origin: "Atlanta, GA",
    destination: "Miami, FL",
    distance: 1060,
    avgTransitHours: 12,
    segments: [
      {
        from: "Atlanta, GA",
        to: "Jacksonville, FL",
        distanceKm: 560,
        mode: "road",
        avgHours: 6,
      },
      {
        from: "Jacksonville, FL",
        to: "Miami, FL",
        distanceKm: 500,
        mode: "road",
        avgHours: 6,
      },
    ],
    waypoints: ["Atlanta, GA", "Jacksonville, FL", "Miami, FL"],
    optimized: true,
  },
  {
    id: "rte_005",
    name: "Asia-Pacific Air Bridge",
    origin: "Shanghai, CN",
    destination: "Tokyo, JP",
    distance: 1750,
    avgTransitHours: 4,
    segments: [
      {
        from: "Shanghai, CN",
        to: "Tokyo, JP",
        distanceKm: 1750,
        mode: "air",
        avgHours: 4,
      },
    ],
    waypoints: ["Shanghai, CN", "Tokyo, JP"],
    optimized: true,
  },
];

export const demoShipments: Shipment[] = [
  {
    id: "shp_001",
    trackingNumber: "AFL-8821-7492-LE",
    carrierId: "car_001",
    origin: "Los Angeles, CA",
    destination: "Seattle, WA",
    status: "in_transit",
    estimatedDelivery: "2026-06-11T14:00:00Z",
    actualDelivery: null,
    weight: 3450,
    packages: 12,
    value: 48500,
    priority: "high",
    customerName: "David Park",
    customerCompany: "Northwind Logistics",
    routeId: "rte_001",
    lastKnownLocation: "Sacramento, CA",
    createdAt: "2026-06-09T06:00:00Z",
    updatedAt: "2026-06-09T11:30:00Z",
  },
  {
    id: "shp_002",
    trackingNumber: "CRR-9931-2250-DM",
    carrierId: "car_003",
    origin: "Chicago, IL",
    destination: "Dallas, TX",
    status: "delayed",
    estimatedDelivery: "2026-06-10T08:00:00Z",
    actualDelivery: null,
    weight: 1280,
    packages: 4,
    value: 22300,
    priority: "medium",
    customerName: "Angela Cross",
    customerCompany: "Meridian Health Partners",
    routeId: "rte_002",
    lastKnownLocation: "St. Louis, MO",
    createdAt: "2026-06-07T12:00:00Z",
    updatedAt: "2026-06-09T09:15:00Z",
  },
  {
    id: "shp_003",
    trackingNumber: "PRE-7741-0910-TH",
    carrierId: "car_002",
    origin: "Dallas, TX",
    destination: "Denver, CO",
    status: "delivered",
    estimatedDelivery: "2026-06-08T18:00:00Z",
    actualDelivery: "2026-06-08T16:22:00Z",
    weight: 5200,
    packages: 18,
    value: 97500,
    priority: "high",
    customerName: "Raj Mehta",
    customerCompany: "Finova Capital",
    routeId: "rte_002",
    lastKnownLocation: "Denver, CO",
    createdAt: "2026-06-05T08:00:00Z",
    updatedAt: "2026-06-08T16:22:00Z",
  },
  {
    id: "shp_004",
    trackingNumber: "GMS-4410-8301-VF",
    carrierId: "car_004",
    origin: "New York, NY",
    destination: "Rotterdam, NL",
    status: "customs_hold",
    estimatedDelivery: "2026-06-22T12:00:00Z",
    actualDelivery: null,
    weight: 18400,
    packages: 240,
    value: 312000,
    priority: "medium",
    customerName: "Claire Bishop",
    customerCompany: "Apex Manufacturing",
    routeId: "rte_003",
    lastKnownLocation: "Rotterdam Port, NL",
    createdAt: "2026-06-01T04:00:00Z",
    updatedAt: "2026-06-09T08:00:00Z",
  },
  {
    id: "shp_005",
    trackingNumber: "SCA-5590-1122-JT",
    carrierId: "car_005",
    origin: "San Francisco, CA",
    destination: "Tokyo, JP",
    status: "in_transit",
    estimatedDelivery: "2026-06-10T22:00:00Z",
    actualDelivery: null,
    weight: 780,
    packages: 3,
    value: 156000,
    priority: "high",
    customerName: "Tomas Berg",
    customerCompany: "Skybridge Aviation",
    routeId: "rte_005",
    lastKnownLocation: "Anchorage, AK",
    createdAt: "2026-06-09T14:00:00Z",
    updatedAt: "2026-06-09T18:45:00Z",
  },
  {
    id: "shp_006",
    trackingNumber: "AFL-6612-9930-XR",
    carrierId: "car_001",
    origin: "Phoenix, AZ",
    destination: "San Diego, CA",
    status: "delivered",
    estimatedDelivery: "2026-06-09T10:00:00Z",
    actualDelivery: "2026-06-09T09:38:00Z",
    weight: 920,
    packages: 2,
    value: 8400,
    priority: "low",
    customerName: "Priya Nair",
    customerCompany: "LegalCore Associates",
    routeId: "rte_001",
    lastKnownLocation: "San Diego, CA",
    createdAt: "2026-06-08T20:00:00Z",
    updatedAt: "2026-06-09T09:38:00Z",
  },
  {
    id: "shp_007",
    trackingNumber: "CRR-3312-4400-PL",
    carrierId: "car_003",
    origin: "Atlanta, GA",
    destination: "Miami, FL",
    status: "delayed",
    estimatedDelivery: "2026-06-11T12:00:00Z",
    actualDelivery: null,
    weight: 2150,
    packages: 7,
    value: 31500,
    priority: "high",
    customerName: "James Okonkwo",
    customerCompany: "Gridpoint Energy",
    routeId: "rte_004",
    lastKnownLocation: "Jacksonville, FL",
    createdAt: "2026-06-08T10:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
  },
  {
    id: "shp_008",
    trackingNumber: "PRE-8850-6622-WQ",
    carrierId: "car_002",
    origin: "Detroit, MI",
    destination: "Nashville, TN",
    status: "in_transit",
    estimatedDelivery: "2026-06-10T16:00:00Z",
    actualDelivery: null,
    weight: 3800,
    packages: 10,
    value: 42800,
    priority: "medium",
    customerName: "Fatima Hassan",
    customerCompany: "MedSupply Direct",
    routeId: "rte_002",
    lastKnownLocation: "Louisville, KY",
    createdAt: "2026-06-08T06:00:00Z",
    updatedAt: "2026-06-09T08:30:00Z",
  },
  {
    id: "shp_009",
    trackingNumber: "SCA-2210-7731-MN",
    carrierId: "car_005",
    origin: "Seattle, WA",
    destination: "London, UK",
    status: "customs_hold",
    estimatedDelivery: "2026-06-13T09:00:00Z",
    actualDelivery: null,
    weight: 560,
    packages: 1,
    value: 289000,
    priority: "high",
    customerName: "Elena Torres",
    customerCompany: "Atlas Freight Logistics",
    routeId: "rte_003",
    lastKnownLocation: "London Heathrow, UK",
    createdAt: "2026-06-08T22:00:00Z",
    updatedAt: "2026-06-09T12:15:00Z",
  },
  {
    id: "shp_010",
    trackingNumber: "GMS-1190-4488-ZB",
    carrierId: "car_004",
    origin: "Houston, TX",
    destination: "Mexico City, MX",
    status: "pending",
    estimatedDelivery: "2026-06-14T10:00:00Z",
    actualDelivery: null,
    weight: 6200,
    packages: 22,
    value: 67300,
    priority: "medium",
    customerName: "Marcus Webb",
    customerCompany: "Pacific Route Express",
    routeId: "rte_004",
    lastKnownLocation: "Houston, TX",
    createdAt: "2026-06-09T07:00:00Z",
    updatedAt: "2026-06-09T07:00:00Z",
  },
  {
    id: "shp_011",
    trackingNumber: "AFL-9999-1111-CV",
    carrierId: "car_001",
    origin: "Denver, CO",
    destination: "Phoenix, AZ",
    status: "cancelled",
    estimatedDelivery: "2026-06-12T15:00:00Z",
    actualDelivery: null,
    weight: 1500,
    packages: 5,
    value: 18900,
    priority: "low",
    customerName: "Sana Iqbal",
    customerCompany: "Continental Rail & Road",
    routeId: "rte_001",
    lastKnownLocation: "Denver, CO",
    createdAt: "2026-06-09T02:00:00Z",
    updatedAt: "2026-06-09T06:45:00Z",
  },
  {
    id: "shp_012",
    trackingNumber: "CRR-4455-6678-RT",
    carrierId: "car_003",
    origin: "Miami, FL",
    destination: "New York, NY",
    status: "in_transit",
    estimatedDelivery: "2026-06-11T08:00:00Z",
    actualDelivery: null,
    weight: 2750,
    packages: 8,
    value: 52100,
    priority: "high",
    customerName: "Tomas Berg",
    customerCompany: "Skybridge Aviation",
    routeId: "rte_004",
    lastKnownLocation: "Richmond, VA",
    createdAt: "2026-06-08T14:00:00Z",
    updatedAt: "2026-06-09T14:20:00Z",
  },
];

export const demoTrackingEvents: TrackingEvent[] = [
  {
    id: "trk_001",
    shipmentId: "shp_001",
    timestamp: "2026-06-09T06:00:00Z",
    location: "Los Angeles, CA",
    status: "picked_up",
    description: "Shipment picked up from origin warehouse",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: "trk_002",
    shipmentId: "shp_001",
    timestamp: "2026-06-09T09:15:00Z",
    location: "Bakersfield, CA",
    status: "in_transit",
    description: "Departed Bakersfield distribution center",
    latitude: 35.3733,
    longitude: -119.0187,
  },
  {
    id: "trk_003",
    shipmentId: "shp_001",
    timestamp: "2026-06-09T11:30:00Z",
    location: "Sacramento, CA",
    status: "in_transit",
    description: "Arrived at Sacramento hub, awaiting relay",
    latitude: 38.5816,
    longitude: -121.4944,
  },
  {
    id: "trk_004",
    shipmentId: "shp_002",
    timestamp: "2026-06-07T12:00:00Z",
    location: "Chicago, IL",
    status: "picked_up",
    description: "Shipment loaded at Chicago warehouse",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: "trk_005",
    shipmentId: "shp_002",
    timestamp: "2026-06-08T16:30:00Z",
    location: "St. Louis, MO",
    status: "in_transit",
    description: "Arrived at St. Louis rail yard",
    latitude: 38.627,
    longitude: -90.1994,
  },
  {
    id: "trk_006",
    shipmentId: "shp_002",
    timestamp: "2026-06-09T08:00:00Z",
    location: "St. Louis, MO",
    status: "delayed",
    description: "Delay: rail car maintenance. Revised ETA pending.",
    latitude: 38.627,
    longitude: -90.1994,
  },
  {
    id: "trk_007",
    shipmentId: "shp_003",
    timestamp: "2026-06-05T08:00:00Z",
    location: "Dallas, TX",
    status: "picked_up",
    description: "Picked up from Dallas fulfilment center",
    latitude: 32.7767,
    longitude: -96.797,
  },
  {
    id: "trk_008",
    shipmentId: "shp_003",
    timestamp: "2026-06-06T14:00:00Z",
    location: "Amarillo, TX",
    status: "in_transit",
    description: "Passing through Amarillo checkpoint",
    latitude: 35.222,
    longitude: -101.8313,
  },
  {
    id: "trk_009",
    shipmentId: "shp_003",
    timestamp: "2026-06-08T16:22:00Z",
    location: "Denver, CO",
    status: "delivered",
    description: "Delivered to recipient. Signed by R. Mehta",
    latitude: 39.7392,
    longitude: -104.9903,
  },
  {
    id: "trk_010",
    shipmentId: "shp_004",
    timestamp: "2026-06-01T04:00:00Z",
    location: "New York, NY",
    status: "departed_port",
    description: "Vessel departed Port of New York",
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    id: "trk_011",
    shipmentId: "shp_004",
    timestamp: "2026-06-08T06:30:00Z",
    location: "Rotterdam Port, NL",
    status: "arrived_port",
    description: "Vessel arrived at Rotterdam port",
    latitude: 51.9244,
    longitude: 4.4777,
  },
  {
    id: "trk_012",
    shipmentId: "shp_004",
    timestamp: "2026-06-09T08:00:00Z",
    location: "Rotterdam, NL",
    status: "customs_hold",
    description: "Customs inspection required. Missing HS code declaration.",
    latitude: 51.9244,
    longitude: 4.4777,
  },
  {
    id: "trk_013",
    shipmentId: "shp_005",
    timestamp: "2026-06-09T14:00:00Z",
    location: "San Francisco, CA",
    status: "picked_up",
    description: "Picked up from SFO cargo terminal",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: "trk_014",
    shipmentId: "shp_005",
    timestamp: "2026-06-09T18:45:00Z",
    location: "Anchorage, AK",
    status: "in_transit",
    description: "Refueling stop at Anchorage. On schedule.",
    latitude: 61.2181,
    longitude: -149.9003,
  },
  {
    id: "trk_015",
    shipmentId: "shp_007",
    timestamp: "2026-06-08T10:00:00Z",
    location: "Atlanta, GA",
    status: "picked_up",
    description: "Picked up from Atlanta distribution hub",
    latitude: 33.749,
    longitude: -84.388,
  },
  {
    id: "trk_016",
    shipmentId: "shp_007",
    timestamp: "2026-06-09T03:00:00Z",
    location: "Jacksonville, FL",
    status: "delayed",
    description: "Vehicle breakdown on I-95. Repair crew dispatched.",
    latitude: 30.3322,
    longitude: -81.6557,
  },
  {
    id: "trk_017",
    shipmentId: "shp_008",
    timestamp: "2026-06-08T06:00:00Z",
    location: "Detroit, MI",
    status: "picked_up",
    description: "Picked up from Detroit depot",
    latitude: 42.3314,
    longitude: -83.0458,
  },
  {
    id: "trk_018",
    shipmentId: "shp_008",
    timestamp: "2026-06-09T08:30:00Z",
    location: "Louisville, KY",
    status: "in_transit",
    description: "Arrived at Louisville sorting facility",
    latitude: 38.2527,
    longitude: -85.7585,
  },
  {
    id: "trk_019",
    shipmentId: "shp_009",
    timestamp: "2026-06-08T22:00:00Z",
    location: "Seattle, WA",
    status: "picked_up",
    description: "Picked up from Seattle air cargo",
    latitude: 47.6062,
    longitude: -122.3321,
  },
  {
    id: "trk_020",
    shipmentId: "shp_009",
    timestamp: "2026-06-09T12:15:00Z",
    location: "London Heathrow, UK",
    status: "customs_hold",
    description: "Held for customs inspection. High-value electronics declaration.",
    latitude: 51.47,
    longitude: -0.4543,
  },
  {
    id: "trk_021",
    shipmentId: "shp_012",
    timestamp: "2026-06-08T14:00:00Z",
    location: "Miami, FL",
    status: "picked_up",
    description: "Picked up from Miami port terminal",
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    id: "trk_022",
    shipmentId: "shp_012",
    timestamp: "2026-06-09T06:00:00Z",
    location: "Savannah, GA",
    status: "in_transit",
    description: "Passing Savannah checkpoint",
    latitude: 32.0809,
    longitude: -81.0912,
  },
  {
    id: "trk_023",
    shipmentId: "shp_012",
    timestamp: "2026-06-09T14:20:00Z",
    location: "Richmond, VA",
    status: "in_transit",
    description: "Arrived Richmond hub. On schedule.",
    latitude: 37.5407,
    longitude: -77.436,
  },
];

export const demoPortDwellRisks: PortDwellRisk[] = [
  {
    shipmentId: "shp_004",
    facility: "Rotterdam Port, NL",
    dwellHours: 25.5,
    freeTimeHoursRemaining: 10,
    riskLevel: "high",
    nextAction: "Pre-clear missing HS code declaration and reserve drayage slot before free time expires.",
    detentionDailyRate: 450,
    estimatedDemurrageCost: 0,
  },
  {
    shipmentId: "shp_009",
    facility: "London Heathrow, UK",
    dwellHours: 14.25,
    freeTimeHoursRemaining: 6,
    riskLevel: "critical",
    nextAction: "Escalate customs broker review for high-value electronics and alert consignee on detention exposure.",
    detentionDailyRate: 625,
    estimatedDemurrageCost: 520,
  },
  {
    shipmentId: "shp_012",
    facility: "Savannah checkpoint",
    dwellHours: 4,
    freeTimeHoursRemaining: 28,
    riskLevel: "medium",
    nextAction: "Confirm receiving appointment and keep a backup carrier on standby for the next dray leg.",
    detentionDailyRate: 195,
    estimatedDemurrageCost: 0,
  },
];

export const demoDockAppointmentRisks: DockAppointmentRisk[] = [
  {
    shipmentId: "shp_002",
    facility: "St. Louis rail yard",
    appointmentWindow: "09:30-10:15 CT",
    appointmentSlotMinutes: 45,
    etaMinutesAway: 42,
    dockTurnMinutes: 90,
    dwellBreakdown: {
      gateToDockMinutes: 18,
      dockToServiceMinutes: 42,
      serviceDurationMinutes: 24,
      serviceToGateOutMinutes: 6,
      dominantPhase: "dock_to_service",
    },
    freightStaged: false,
    checkInMode: "manual",
    gateValidationStatus: "missing",
    preArrivalPacketStatus: "missing_vehicle_id",
    sealVerificationStatus: "pending_verification",
    dockSafetyInterlockStatus: "restraint_pending",
    trailerSupportStatus: "fixed_jacks_verified",
    coldChainStatus: "pre_cool_pending",
    emptyTrailerRemovalStatus: 'hostler_queued',
    carrierArrivalStatus: 'late_risk',
    noShowRecoveryStatus: 'monitor_check_in',
    assignedDockDoor: 'Dock 7',
    dockDoorAssignmentStatus: "reassignment_required",
    dockFlowDirection: "inbound",
    dockDoorFlowConflict: "inbound_overrun",
    laborReadiness: "crew_shortfall",
    equipmentReadiness: "forklift_unavailable",
    trailerSpottingStatus: "spotter_queued",
    spotMoveEtaMinutes: 12,
    spotMoveWaitMinutes: 6,
    spotMoveSlaMinutes: 15,
    receiverConstraint: "yard_congestion",
    rescheduleByMinutes: 20,
    cutoffRiskMinutes: 35,
    detentionFreeMinutes: 60,
    detentionHourlyRate: 65,
    estimatedDetentionCost: 33,
    detentionResponsibility: "facility",
    detentionEvidenceStatus: "missing_timestamps",
    status: "at_risk",
    mitigation:
      "Clear the inbound overrun by reassigning the truck from congested Dock 7 to a 90-minute unloading slot before the 35-minute shipping cutoff, monitor the carrier check-in and alert the dock coordinator if it is not confirmed within 15 minutes of the appointment start, have the yard hostler pull the completed empty trailer off Dock 7 so the reassigned slot can be spotted, dispatch and escalate the yard spotter because 6 minutes waiting plus a 12-minute move projects an 18-minute turn against the 15-minute call-to-door target, stage receiving labor and reserve a forklift now, capture the tractor vehicle ID in the carrier portal, verify the trailer seal and record chain-of-custody evidence at the gate, keep fixed jacks supporting the uncoupled trailer, engage and confirm the trailer restraint before enabling the dock leveler, complete the leveler inspection, send a digital gate pass before arrival, confirm reefer pre-cool and set-point verification with the carrier so the cold-chain load arrives within range, and capture the gate check-in and door-release timestamps so the facility-side delay is absorbed internally instead of misbilled to the carrier.",
  },
  {
    shipmentId: "shp_007",
    facility: "Jacksonville cross-dock",
    appointmentWindow: "11:00-12:30 ET",
    appointmentSlotMinutes: 90,
    etaMinutesAway: 28,
    dockTurnMinutes: 75,
    dwellBreakdown: {
      gateToDockMinutes: 10,
      dockToServiceMinutes: 8,
      serviceDurationMinutes: 46,
      serviceToGateOutMinutes: 11,
      dominantPhase: "service_duration",
    },
    freightStaged: true,
    checkInMode: "digital",
    gateValidationStatus: "validated",
    preArrivalPacketStatus: "complete",
    sealVerificationStatus: "verified_intact",
    dockSafetyInterlockStatus: "verified_ready",
    trailerSupportStatus: "tractor_coupled",
    coldChainStatus: "within_range_verified",
    emptyTrailerRemovalStatus: 'removed_door_released',
    carrierArrivalStatus: 'on_schedule',
    noShowRecoveryStatus: 'not_required',
    assignedDockDoor: 'Dock 4',
    dockDoorAssignmentStatus: "confirmed",
    dockFlowDirection: "outbound",
    dockDoorFlowConflict: "none",
    laborReadiness: "crew_confirmed",
    equipmentReadiness: "ready",
    trailerSpottingStatus: "spotted_at_door",
    spotMoveEtaMinutes: 0,
    spotMoveWaitMinutes: 0,
    spotMoveSlaMinutes: 15,
    receiverConstraint: "none",
    rescheduleByMinutes: null,
    cutoffRiskMinutes: null,
    detentionFreeMinutes: 120,
    detentionHourlyRate: 70,
    estimatedDetentionCost: 0,
    detentionResponsibility: "carrier",
    detentionEvidenceStatus: "evidence_complete",
    status: "ready",
    mitigation:
      "Keep the tractor coupled and Dock 4 reserved with the trailer restraint engaged, the dock leveler verified ready, and the reefer set point confirmed within range, then notify the forklift lead when the truck crosses the 15-minute geofence. All four detention timestamps (gate arrival, check-in, service complete, gate departure) are captured, so the zero-cost stay leaves nothing to dispute.",
  },
  {
    shipmentId: "shp_012",
    facility: "Richmond hub",
    appointmentWindow: "15:00-15:30 ET",
    appointmentSlotMinutes: 30,
    etaMinutesAway: 18,
    dockTurnMinutes: 80,
    dwellBreakdown: {
      gateToDockMinutes: 30,
      dockToServiceMinutes: 20,
      serviceDurationMinutes: 20,
      serviceToGateOutMinutes: 10,
      dominantPhase: "gate_to_dock",
    },
    freightStaged: false,
    checkInMode: "digital",
    gateValidationStatus: "needs_review",
    preArrivalPacketStatus: "cargo_mismatch",
    sealVerificationStatus: "damaged_hold",
    dockSafetyInterlockStatus: "leveler_fault_hold",
    trailerSupportStatus: "support_required_hold",
    coldChainStatus: "temperature_excursion_hold",
    emptyTrailerRemovalStatus: 'removal_unplanned',
    carrierArrivalStatus: 'no_show_review',
    noShowRecoveryStatus: 'operator_confirmation_required',
    assignedDockDoor: null,
    dockDoorAssignmentStatus: "unassigned",
    dockFlowDirection: "outbound",
    dockDoorFlowConflict: "outbound_pickup_at_risk",
    laborReadiness: "crew_shortfall",
    equipmentReadiness: "ready",
    trailerSpottingStatus: "trailer_location_unverified",
    spotMoveEtaMinutes: null,
    spotMoveWaitMinutes: null,
    spotMoveSlaMinutes: 15,
    receiverConstraint: "receiver_closed",
    rescheduleByMinutes: 10,
    cutoffRiskMinutes: 12,
    detentionFreeMinutes: 45,
    detentionHourlyRate: 85,
    estimatedDetentionCost: 50,
    detentionResponsibility: "unattributed",
    detentionEvidenceStatus: "conflicting_timestamps",
    status: "blocked",
    mitigation:
      "Protect the outbound pickup from the shared-door conflict: place the damaged trailer seal under a chain-of-custody security hold, verify fixed jacks support the uncoupled trailer before forklift entry to prevent upending, isolate the failed dock leveler for repair and keep the trailer restraint engaged, keep the dock door unassigned, locate and verify the trailer in the yard before dispatching a spotter, treat the appointment as a potential no-show until carrier check-in is confirmed, have the dock coordinator confirm the slot is empty before releasing it for reassignment, confirm outbound crew coverage, escalate staging immediately, confirm the cargo count against the appointment packet, and rebook before the receiver closes at 15:30 because the 12-minute cutoff risk is inside the live ETA window, create a removal plan for the empty trailer still blocking the dock lane, quarantine the temperature-excursion load for QA review with the reefer unit download captured before any dock service, and reconcile the conflicting ELD geofence and facility gate-log arrival timestamps with the driver while holding the detention estimate in billing review until the clock chain agrees before any carrier chargeback.",
  },
];

export const demoMetrics: WarehouseMetrics = {
  activeShipments: 8,
  onTimeRate: 87,
  avgTransitDays: 3.4,
  activeAlerts: 4,
  totalCarriers: 5,
  totalInTransit: 4,
  delayedCount: 4,
  deliveredToday: 2,
};
